---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth-forward
  namespace: traefik
spec:
  forwardAuth:
    address: http://oauth2-proxy.oauth2-proxy/oauth2/auth
    trustForwardHeader: true
    authResponseHeaders:
      - "X-Forwarded-User"
      - "Authorization"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth-{{.Runtime.Name}}
  namespace: traefik
spec:
  chain:
    middlewares:
    - name: oauth-errors-{{.Runtime.Name}}
    - name: oauth-forward
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth-errors-{{.Runtime.Name}}
  namespace: traefik
spec:
  errors:
    status:
      - "401"
    service:
      name: oauth2-proxy
      namespace: oauth2-proxy
      port: 80
    query: {{printf "/oauth2/sign_in?rd=https://tekton.%s.%s.nip.io:%s" .Runtime.Name .Runtime.Apiserver .Traefik.HttpsNodePort}}
