{{- range $index, $name := .VclusterNames }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth-{{$item.Name}}
  namespace: traefik
spec:
  chain:
    middlewares:
    - name: oauth-errors-{{$item.Name}}
    - name: oauth-forward
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth-errors-{{$item.Name}}
  namespace: traefik
spec:
  errors:
    status:
      - "401"
    service:
      name: {{.$item.HostCluster.Name}}-oauth2-proxy
      namespace: oauth2-proxy
      port: 80
    query: {{printf "/oauth2/sign_in?rd=https://tekton.%s.%s.nip.io:%s" $item.Name $item.HostCluster.Name .Traefik.HttpsNodePort}}
{{- end}}

