apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
spec:
  project: {{.Runtime.Name }}-runtime-project
  source:
    path: runtimes/{{.Runtime.Name}}-runtime/argoevents/overlays/production
    repoURL: {{.RepoURL}}
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
