apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton
  namespace: argocd
spec:
  project: {{.Runtime.Name}}-runtime-project
  source:
    path: runtimes/{{.Runtime.Name}}-runtime/tekton/overlays/production
    repoURL: {{.RepoURL}}
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-pipelines
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
