apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  {{printf "%s-traefik-resources" .Runtime.Name}}
  namespace: argocd
spec:
  project: {{.Runtime.ArgocdProject}}
  source:
    path: traefik/overlays/production
    repoURL: {{.RepoURL}}
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true