apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{printf "%s-oauth2-proxy" .HostCluster.Name}}
  namespace: argocd
spec:
  project: dev-tenant
  source:
    chart: oauth2-proxy
    repoURL: https://oauth2-proxy.github.io/manifests
    targetRevision: 6.12.0
    helm:
      values: |-
        config:
          clientID: {{.OauthConfigs.ClientID}}
          clientSecret: {{.OauthConfigs.ClientSecret}}

        extraArgs:
          provider: "oidc"
          provider-display-name: "Dex"
          whitelist-domain: "{{printf ".%s.nip.io:%s" .HostCluster.Apiserver .Traefik.HttpsNodePort}}"
          cookie-secure: "true"
          cookie-domain: "{{printf ".%s.nip.io" .Vcluster.HostCluster.Apiserver}}"
          redirect-url: {{printf "https://auth.%s.%s.nip.io:%s/oauth2/callback" .HostCluster.Name .HostCluster.Apiserver .Traefik.HttpsNodePort}}
          cookie-secret: "0d6a5698b9d52e612a6cb7161e747817"
          oidc-issuer-url: "{{.OauthConfigs.Issuer}}"
          scope: "openid profile email groups"
          email-domain: "*"
          skip-provider-button: "false"
          set-authorization-header: "true"

        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: traefik
          tls:
            - hosts:
                - {{printf "auth.%s.%s.nip.io" .HostCluster.Name .HostCluster.Apiserver}}
          path: /
          pathType: ImplementationSpecific
          hosts:
            - {{printf "auth.%s.%s.nip.io" .HostCluster.Name .HostCluster.Apiserver}}

        extraVolumes:
          - name: ca-bundle-cert
            secret:
              secretName: idp-ca-secret

        extraVolumeMounts:
          - mountPath: /etc/ssl/certs/
            name: ca-bundle-cert
  destination:
    server: {{.HostCluster.ApiServer}}
    namespace: oauth2-proxy
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
