apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{printf "%s-traefik" .HostCluster.Name}}
  namespace: argocd
spec:
  project: {{.HostCluster.ArgocdProject}}
  source:
    chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: v10.22.0
    helm:
      values: |-
        ports:
          traefik:
            port: 9000
          web:
            nodePort: {{.Traefik.HttpNodePort}}
          websecure:
            nodePort: {{.Traefik.HttpsNodePort}}
            tls:
              enabled: true
        providers:
          kubernetesIngress:
            publishedService:
              enabled: true
  destination:
    server: {{.HostCluster.ApiServer}}
    namespace: traefik
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

