apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  {{printf "%s-vcluster-initial" .Vcluster.Name}}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  project: {{.NautesConfigs.TenantName}}
  source:
    path: host-clusters/{{.Vcluster.HostCluster.Name}}/vclusters/{{.Vcluster.Name}}/vcluster-initial
    repoURL: {{.RepoURL}}
    targetRevision: HEAD
  destination:
    server: {{.Vcluster.HostCluster.ApiServer}}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
